### ISSUE TITLE
Compilation errors when used with the latest sark_grids

### ISSUE THREAD

**Issue by rwygand** [sarkahn/adam_fov_rs#2]
It looks like some of the methods have changed names in sark_grids, particularly the index -> pos and pos -> index (not called transform_lti, etc).

**Comment by rwygand** [comment]
here's a small diff of what I had to change to get this to work with sark_grids 0.5.7:

```
diff --git a/src/lib.rs b/src/lib.rs
index 8b2694f..aaa584f 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -82,12 +82,12 @@ pub trait VisibilityMapUtility {
 
 impl VisibilityMapUtility for VisibilityMap2d {
     fn toggle_opaque(&mut self, p: impl GridPoint) {
-        let i = self.pos_to_index(p);
+        let i = self.transform_lti(p);
         self[i].opaque = !self[i].opaque;
     }
 
     fn toggle_visible(&mut self, p: impl GridPoint) {
-        let i = self.pos_to_index(p);
+        let i = self.transform_lti(p);
         self[i].visible = !self[i].visible;
     }
 
@@ -417,7 +417,7 @@ mod test {
 
     #[test]
     fn test_fov() {
-        let mut map = VisibilityMap2d::default([30, 30]);
+        let mut map = VisibilityMap2d::new([30, 30]);
         map[[0, 1]].opaque = true;
         map[[1, 0]].opaque = true;
         fov::compute([0, 0], 5, &mut map);
```

I was going to post a PR, but I'm seeing some of the examples fail to compile and I'm not yet familiar enough with all of these systems
